again

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -42,15 +42,14 @@ fi
 echo $INSTALL_VERSION_OPTION
 
 # Install Node.js using prebuilt binaries
-# https://nodejs.org/dist/v20.9.0/node-v20.9.0.tar.xz
 echo "Installing Node.js..."
-NODE_VERSION=${NODE_VERSION:-20.9.0} # Default to Node.js 14.17.0 if NODE_VERSION is not set
+NODE_VERSION=${NODE_VERSION:20.9.0} # Default to Node.js 14.17.0 if NODE_VERSION is not set
 NODE_DISTRO="node-v$NODE_VERSION-linux-x64"
 NODE_TAR="$NODE_DISTRO.tar.xz"
 NODE_URL="https://nodejs.org/dist/v$NODE_VERSION/$NODE_TAR"
 
 curl -O $NODE_URL
-tar -xf $NODE_TAR
+tar -xf $NODE_TAR || { echo "Error extracting Node.js tarball"; exit 1; }
 mv $NODE_DISTRO $HEROKU_DIR/node
 rm $NODE_TAR
 
